### ISSUE TITLE
verilator platform for manycore simulation

### ISSUE THREAD

**Issue by alittlerice** [bespoke-silicon-group/bsg_replicant#640]
Hi,

I'm trying to use dpi-verilator for manycore simulation. After setting up as instructed and typing "make regression", I received the following error:

../bsg_bladerunner/bsg_replicant/libraries/bsg_manycore_features.h:38:2: error: #error "_BSG_SOURCE not defined: required for bsg_manycore_runtime"
   38 | #error "_BSG_SOURCE not defined: required for bsg_manycore_runtime"
      |  ^~~~~

Please advise how it could be resolved. Thank you.

**Comment by drichmond** [comment]
Huh, that looks like a typo and should be `_BSD_SOURCE`

What kind of system are you running on?

**Comment by alittlerice** [comment]
Hi Dustin,

It's the correct spelling of the error and it's generated from the file:
bsg_bladerunner/bsg_replicant/libraries/bsg_manycore_features.h

I'm running on ubuntu 20.04. 

Thank you!

**Comment by alittlerice** [comment]
Hi Dustin,

Should we correct the typo in the source file?

I'm running on ubuntu 20.04.

Thank you!

**Comment by drichmond** [comment]
The typo is in our source. It should be _BSD_SOURCE, not _BSG_SOURCE. 

@mrutt92 Can you take a look if you have a moment?

**Comment by mrutt92** [comment]
```c
#ifndef _BSD_SOURCE
#error "_BSG_SOURCE not defined: required for bsg_manycore_runtime"
#endif
```

It's a typo.

**Comment by mrutt92** [comment]
You can correct the typo but it won't make your code compile.  Define _BSD_SOURCE on the command line to fix your problem.

**Comment by mrutt92** [comment]
@alittlerice do you have the full trace from running `make regression`? _BSD_SOURCE is supposed to be defined by the makefile flow but this error would suggest that's not happening.

**Comment by alittlerice** [comment]
@mrutt92  I do have the full trace but it would be too much to attach it here. What info would you want to check and how the _BSD_SOURCE is supposed to be defined? Thank you.

**Comment by alittlerice** [comment]
@mrutt92 ,
Attached is the log file indicating the error. Thank you.

[mylog-.txt](https://github.com/bespoke-silicon-group/bsg_replicant/files/5432389/mylog-.txt)

**Comment by mrutt92** [comment]
The makefile flow is supposed to define it for you.

**Comment by alittlerice** [comment]
Did you see any issues with the flow shown in the log file that generates the error? Thank you.

**Comment by mrutt92** [comment]
Nothing jumps out. The macros seem to be defined by the flow. These macros are used by your system headers for comparability. We use them to hav system support for endianness swap functions. Something you could try is editing the makefiles in the examples/<suite-name> directory and making sure _BSD_SOURCE defined as “1” instead of just defined as empty.

**Comment by drichmond** [comment]
I think the problem is that _GNU_SOURCE used to cause _BSD_SOURCE to be defined. In the verison of RHEL that we test in, this is the case. 

You can read about it more here: 
https://man7.org/linux/man-pages/man7/feature_test_macros.7.html


I've gone ahead and fixed the issue in this branch/PR: 

https://github.com/bespoke-silicon-group/bsg_replicant/tree/ubuntu_support


That being said, the manycore toolchain will also fail to build in Ubuntu. BUT, fortunately for you, I already fixed those issues too: 

https://github.com/bespoke-silicon-group/bsg_manycore/tree/ci_ubuntu_support

The issue there is that we use the `cmake3` command to build, and depend on devtools-8. Both of these are RHEL-specific. The latter has two issues filed: https://github.com/bespoke-silicon-group/bsg_manycore/issues/391 and https://github.com/bespoke-silicon-group/bsg_manycore/issues/334. Both issues are fixed in the branch above.

**Comment by alittlerice** [comment]
@drichmond Thank you!

**Comment by alittlerice** [comment]
@drichmond 

After running make regression, I'm still getting the following error message:

usr/include/features.h:187:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
    187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
   cc1plus: all warnings being treated as errors

**Comment by drichmond** [comment]
Huh, are you compiling with -wall? 

In the makefiles that were edited in the PR, you can simply replace _BSD_SOURCE with _DEFAULT_SOURCE like it says in the error message

**Comment by alittlerice** [comment]
Yes I did and things go well until I tried to run the regression tests for python. Here is the error message:

g++ -std=c++11 test_loader.o -o test_loader -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -L/usr/lib  -lcrypt -lpthread -ldl  -lutil -lm -lm  -fPIE -lbsg_manycore_runtime -L/home/.../bsg/bsg_bladerunner/bsg_replicant/libraries/platforms/dpi-verilator -Wl,-rpath=/home/.../bsg/bsg_bladerunner/bsg_replicant/libraries/platforms/dpi-verilator -lmachine -L/home/.../bsg/bsg_bladerunner/bsg_replicant/machines/baseline_v0_8_4 -Wl,-rpath=/home/.../bsg/bsg_bladerunner/bsg_replicant/machines/baseline_v0_8_4 -lm
/usr/bin/ld: test_loader.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make: *** [/home/.../bsg/bsg_bladerunner/bsg_replicant/libraries/platforms/dpi-verilator/link.mk:129: test_loader] Error 1

**Comment by save-buffer** [comment]
I have a PR out that fixes those as well (#642). In the meantime you can check out the `sasha_ubuntu` branch which should make it work on Ubuntu (my testing was done in a debian docker container, but it should still work).

**Comment by alittlerice** [comment]
@save-buffer Thank you!
